version: '3.8'

services:
  simplecloud:
    build: .
    container_name: simplecloud-manager
    restart: unless-stopped
    volumes:
      - ./storage:/opt/simplecloud/storage
      - ./templates:/opt/simplecloud/templates
      - ./modules:/opt/simplecloud/modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_ENABLED=true
      - JAVA_OPTS=-Xmx2G -Xms1G
    networks:
      - simplecloud-network
    ports:
      - "1630:1630"

  version-monitor:
    image: alpine:latest
    container_name: simplecloud-version-monitor
    restart: unless-stopped
    command: |
      sh -c "
        apk add --no-cache curl jq
      
        while true; do
          echo 'Checking for updates...'
      
          touch /versions/check_trigger
      
          sleep 7200
        done
      "
    volumes:
      - version-check:/versions
    networks:
      - simplecloud-network

networks:
  simplecloud-network:
    driver: bridge

volumes:
  version-check: